version: 2.1

executors:
  python-executor:
    docker:
      - image: python:latest
    working_directory: $CIRCLE_WORKING_DIRECTORY

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: python-package-build
          command: python sdist bdist_wheel
      - persist_to_workspace:
          root: jenkins-workspace
          paths:
            - dist

  tests:
    executor: python-executor
    steps:
      - attach_workspace:
          at: $CIRCLE_WORKING_DIRECTORY/jenkins-workspace
      - run:
          name: python-package-test
          command: |
            source tests/functional_test.sh
            prereq_install
            backup_test
            restore_test

workflows:
  version: 2

  jenkins-backup-restore-cli:
    jobs:
      - build
      - tests:
          requires:
            - build