version: 2.1

jobs:
  build:
    build:
    docker: 
      - image: python:latest
    steps:
      - checkout
      - run: python setup.py install --user
      - run: python3 jenkins_backup_restore_cli/jenkins_backup_restore_cli.py --help
