version: 2.1

jobs:
  build:
    build:
    docker: 
      - image: python:latest
    steps:
      - checkout
      - run: python setup.py install --user
      - run: jenkins-backup-restore-cli --help
