version: 2.1

executors:
  python-executor:
    docker:
      - image: python:latest
    working_directory: jenkins-ci

jobs:
  build:
    executor: python-executor
    steps:
      - run: mkdir src
      - checkout:
          path: jenkins-ci/src
      - run:
          name: python-package-build
          command: |
            pip install --upgrade setuptools
            python3 setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: jenkins-ci/src
          paths:
            - dist
            - tests
            - '*.py'

  tests:
    executor: python-executor
    steps:
      - attach_workspace:
          at: src
      - run:
          name: python-package-test
          command: |
            source tests/functional_test.sh
            prereq_install
            backup_test
            restore_test

workflows:
  version: 2

  jenkins-backup-restore-cli:
    jobs:
      - build
      - tests:
          requires:
            - build
