version: 2.1

executors:
  python-executor:
    docker:
      - image: python:latest
    working_directory: jenkins-ci

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: python-package-build
          command: |
            pip install --upgrade setuptools
            python3 setup.py sdist bdist_wheel

  tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: python-package-test
          command: |
            ls -la
            chmod 700 tests/functional_tests.sh
            source tests/functional_tests.sh
            prereq_install
            backup_test
            restore_test

workflows:
  version: 2

  jenkins-backup-restore-cli:
    jobs:
      - build
      - tests:
          requires:
            - build
