apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ .Values.image.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRepository }}/{{ .Values.image.imageName }}:{{ .Values.image.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.envVars }}
          env:
            {{-  with .Values.envVars}}{{ . | toYaml | trim | nindent 12 }}{{ end }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ required "You must provide a volume mount via .Values.volumeMountPath!" .Values.volumes.mountPath }}
              name: {{ .Values.volumes.volumeName }}
      volumes:
        - name: {{ .Values.volumes.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.persistentVolumeClaimName }}
